let collegeName="CDC Deemed to University";
console.log(collegeName);
let collegeN=new String("CDC college");
console.log(collegeN);
console.log(collegeName.length);
console.log(collegeName.toLowerCase());
console.log(collegeName.toUpperCase());
console.log(collegeName.charAt('2'));
console.log(collegeName.startsWith('cdc'));
console.log(collegeName.startsWith('CDC'));
console.log(collegeName.endsWith('university'));
console.log(collegeName.endsWith('UNIVERSITY'));
console.log(collegeName.includes('college'));
console.log(collegeName.includes('COLLEGE'));
console.log(collegeName.repeat('4'));
console.log(`Hi Everyone i studied in ${collegeName}`);